-- ===========================================================================
-- Better Days — database schema (Postgres / Netlify Database)
-- Idempotent: safe to run repeatedly. Applied by `npm run db:migrate`.
-- ===========================================================================

-- --- Auth.js (NextAuth) tables -------------------------------------------------
-- Shape required by @auth/pg-adapter. Integer identity PKs.

CREATE TABLE IF NOT EXISTS users (
  id                SERIAL PRIMARY KEY,
  name              VARCHAR(255),
  email             VARCHAR(255) UNIQUE,
  "emailVerified"   TIMESTAMPTZ,
  image             TEXT,
  -- Better Days additions:
  password_hash     TEXT,                                   -- Credentials provider
  display_name      TEXT,
  timezone          TEXT,                                   -- required for reminders
  plan              TEXT NOT NULL DEFAULT 'free',           -- extension point: 'free' | 'premium'
  is_admin          BOOLEAN NOT NULL DEFAULT FALSE,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,          -- admin can disable an abusive account
  onboarded_at      TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_active_at    TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS accounts (
  id                  SERIAL PRIMARY KEY,
  "userId"            INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type                VARCHAR(255) NOT NULL,
  provider            VARCHAR(255) NOT NULL,
  "providerAccountId" VARCHAR(255) NOT NULL,
  refresh_token       TEXT,
  access_token        TEXT,
  expires_at          BIGINT,
  id_token            TEXT,
  scope               TEXT,
  session_state       TEXT,
  token_type          TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
  id             SERIAL PRIMARY KEY,
  "userId"       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires        TIMESTAMPTZ NOT NULL,
  "sessionToken" VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS verification_token (
  identifier TEXT NOT NULL,
  expires    TIMESTAMPTZ NOT NULL,
  token      TEXT NOT NULL,
  PRIMARY KEY (identifier, token)
);

-- --- Application tables -------------------------------------------------------

CREATE TABLE IF NOT EXISTS habits (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  type            TEXT NOT NULL CHECK (type IN ('build', 'break')),
  category        TEXT,                    -- drives the habit icon badge
  unit            TEXT,                    -- e.g. 'piece', 'minute', 'walk'
  baseline_value  NUMERIC,                 -- nullable: the user's historical "usual"
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at     TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS habits_user_id_idx ON habits(user_id);

CREATE TABLE IF NOT EXISTS log_entries (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  habit_id    BIGINT NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value       NUMERIC NOT NULL DEFAULT 1,
  kind        TEXT NOT NULL DEFAULT 'good' CHECK (kind IN ('good', 'slip')),
  note        TEXT,                        -- the context: "1 slice at a birthday party"
  logged_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS log_entries_habit_logged_idx ON log_entries(habit_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS log_entries_user_logged_idx  ON log_entries(user_id, logged_at DESC);

CREATE TABLE IF NOT EXISTS reminders (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  habit_id     BIGINT NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_of_day  TIME NOT NULL,
  timezone     TEXT,                       -- snapshot of the user's tz at save time
  enabled      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- No UNIQUE(habit_id): free tier writes exactly one row per habit, but the
-- table already supports multiple/custom reminders for a future premium tier.
CREATE INDEX IF NOT EXISTS reminders_habit_id_idx ON reminders(habit_id);

-- Web Push subscriptions (one per browser/device). Used by the reminder
-- delivery job, which is stubbed for now.
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint    TEXT NOT NULL UNIQUE,
  p256dh      TEXT NOT NULL,
  auth        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_id_idx ON push_subscriptions(user_id);
